# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_classifier.ipynb (unless otherwise specified).

__all__ = ['_BinInspector', '_MultiInspector']

# Cell
from .any_model import _Inspector

# Cell
class _BinInspector(_Inspector):
    pass

# Cell
class _MultiInspector(_Inspector):
    pass

# Cell
#nbdev_comment _all_ = ["_BinInspector", "_MultiInspector"]