# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_linear_model.ipynb (unless otherwise specified).

__all__ = ['_LinRegInspector', '_LinBinInspector', '_LinMultiInspector']

# Cell
from .regressor import _RegInspector

# Cell
class _LinRegInspector(_RegInspector):
    pass

# Cell
from .classifier import _BinInspector, _MultiInspector

# Cell
class _LinBinInspector(_BinInspector):
    pass

# Cell
class _LinMultiInspector(_MultiInspector):
    pass

# Cell
#nbdev_comment _all_ = ["_LinRegInspector", "_LinBinInspector", "_LinMultiInspector"]