# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_regressor.ipynb (unless otherwise specified).

__all__ = ['_RegInspector']

# Cell
from .any_model import _Inspector

# Cell
class _RegInspector(_Inspector):
    pass

# Cell
#nbdev_comment _all_ = ["_RegInspector"]