# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08_searchcv_estimator.ipynb (unless otherwise specified).

__all__ = ['_SearchCVInspector']

# Cell
from sklearn.model_selection._search import BaseSearchCV

from .any_model import _Inspector

# Cell
class _SearchCVInspector(_Inspector):
    pass

# Cell
#nbdev_comment _all_ = ["_SearchCVInspector"]