# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/07_tree.ipynb (unless otherwise specified).

__all__ = ['_TreeRegInspector', '_TreeBinInspector', '_TreeMultiInspector']

# Cell
from .regressor import _RegInspector

# Cell
class _TreeRegInspector(_RegInspector):
    pass

# Cell
from .classifier import _BinInspector, _MultiInspector

# Cell
class _TreeBinInspector(_BinInspector):
    pass

# Cell
class _TreeMultiInspector(_MultiInspector):
    pass

# Cell
#nbdev_comment _all_ = ["_TreeRegInspector", "_TreeBinInspector", "_TreeMultiInspector"]