# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_tree.ipynb.

# %% auto 0
__all__ = ['_TreeRegInspector', '_TreeBinInspector', '_TreeMultiInspector']

# %% ../nbs/08_tree.ipynb 3
from typing import Optional

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.axes import Axes
from ..delegate import delegates
from .any_model import _Inspector
from .classifier import _BinInspector, _MultiInspector
from .regressor import _RegInspector
from sklearn.tree import plot_tree

# %% ../nbs/08_tree.ipynb 4
class _TreeMixin(_Inspector):
    """Mixin for decision tree model inspectors"""

    @delegates(plot_tree)
    def plot_tree(self, ax: Optional[Axes] = None, **kwargs):
        """Show decision tree"""
        if ax is None:
            # these dimensions seem to work well empirically
            max_size = 50
            depth = (
                kwargs["max_depth"] + 1
                if "max_depth" in kwargs
                else self.model.get_depth()
            )
            fig_height = min(depth * 2.2, max_size)
            width = (
                2 * kwargs["max_depth"]
                if "max_depth" in kwargs
                else self.model.get_n_leaves()
            )
            fig_width = min(width * 3.5, max_size)
            _, ax = plt.subplots(figsize=(fig_width, fig_height))
        kwargs = {"filled": True, "fontsize": 12, **kwargs}
        return plot_tree(
            self.model,
            feature_names=self.X.columns,
            class_names=np.unique(self.y).astype(str),
            ax=ax,
            **kwargs,
        )[0].axes

# %% ../nbs/08_tree.ipynb 6
class _TreeRegInspector(_RegInspector, _TreeMixin):
    """Inspector for decision tree regressors models"""

    pass

# %% ../nbs/08_tree.ipynb 9
class _TreeBinInspector(_BinInspector, _TreeMixin):
    """Inspector for binary decision tree models"""

    pass

# %% ../nbs/08_tree.ipynb 12
class _TreeMultiInspector(_MultiInspector, _TreeMixin):
    """Inspector for multiclass decision tree models"""

    pass

# %% ../nbs/08_tree.ipynb 14
_all_ = ["_TreeRegInspector", "_TreeBinInspector", "_TreeMultiInspector"]
