# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"COLORS": "00_inspect.ipynb",
         "Inspector": "00_inspect.ipynb",
         "LinRegInspector": "00_inspect.ipynb",
         "LogRegInspector": "00_inspect.ipynb",
         "calculate_metrics_by_thresh": "01_tune.ipynb",
         "coverage": "01_tune.ipynb",
         "calculate_metric_ignoring_nan": "01_tune.ipynb",
         "fbeta": "01_tune.ipynb",
         "plot_correlation": "02_explore.ipynb"}

modules = ["inspect.py",
           "tune.py",
           "explore.py"]

doc_url = "https://gsganden.github.io/model_inspector/"

git_url = "https://github.com/gsganden/model_inspector/tree/master/"

def custom_doc_links(name): return None
