# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"COLORS": "00_inspect.ipynb",
         "get_inspector": "00_inspect.ipynb",
         "identify_type": "00_inspect.ipynb",
         "ModelType": "00_inspect.ipynb",
         "generate_model_html": "00_inspect.ipynb",
         "calculate_metrics_by_thresh_binary": "01_tune.ipynb",
         "calculate_metrics_by_thresh_multi": "01_tune.ipynb",
         "coverage": "01_tune.ipynb",
         "calculate_metric_ignoring_nan": "01_tune.ipynb",
         "fbeta": "01_tune.ipynb",
         "confusion_matrix": "01_tune.ipynb",
         "show_correlation": "02_explore.ipynb",
         "plot_column_clusters": "02_explore.ipynb",
         "delegates": "03_delegate.ipynb"}

modules = ["inspect.py",
           "tune.py",
           "explore.py",
           "delegate.py"]

doc_url = "https://gsganden.github.io/model_inspector/"

git_url = "https://github.com/gsganden/model_inspector/tree/main/"

def custom_doc_links(name): return None
