# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_colors.ipynb.

# %% auto 0
__all__ = ['COLORS']

# %% ../nbs/11_colors.ipynb 3
COLORS = {"blue": "#377eb8", "orange": "#ff7f00", "green": "#4daf4a", "pink": "#f781bf"}
