ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "model_inspector"
  site-url: "https://gsganden.github.io/model_inspector/"
  description: "Inspect machine learning models"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-url: "https://github.com/gsganden/model_inspector/tree/main/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/gsganden/model_inspector/tree/main/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
