name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check linting
      run: |
        pip install black flake8 nbqa
        pwd
        ls
        nbqa black --check ../nbs
        nbqa flake8 ../nbs
    - uses: fastai/workflows/nbdev-ci@master
      