name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: fastai/workflows/nbdev-ci@master
    - name: Check linting
      run: |
        echo "hi1"
        pwd
        echo "hi2"
        ls
        echo "hi3"
        pip install black flake8 nbqa
        echo "hi4"
        nbqa black --check ../nbs
        nbqa flake8 ../nbs
      