name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: fastai/workflows/nbdev-ci@master
    - name: Lint
      run: |
        pip install black flake8 nbqa
        nbqa black --check nbs
        nbqa flake8 nbs
      